<?php

use Illuminate\Database\Seeder;

class UGMTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ugm')->insert([
        	'fakultas' => 'BIOLOGI', 'EKONOMIKA DAN BISNIS', 'EKONOMIKA DAN BISNIS', 'EKONOMIKA DAN BISNIS', 'FARMASI', 'FILSAFAT', 'GEOGRAFI', 'GEOGRAFI', 'GEOGRAFI', 'HUKUM', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ILMU BUDAYA', 'ISIPOL', 'ISIPOL', 'ISIPOL', 'ISIPOL', 'ISIPOL', 'ISIPOL', 'KEDOKTERAN', 'KEDOKTERAN', 'KEDOKTERAN', 'KEDOKTERAN GIGI', 'KEDOKTERAN GIGI', 'KEDOKTERAN HEWAN', 'KEHUTANAN', 'MIPA', 'MIPA', 'MIPA', 'MIPA', 'MIPA', 'MIPA', 'MIPA', 'PERTANIAN', 'PERTANIAN', 'PERTANIAN', 'PERTANIAN', 'PERTANIAN', 'PERTANIAN', 'PERTANIAN', 'PERTANIAN', 'PERTANIAN', 'PETERNAKAN', 'PSIKOLOGI', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNIK', 'TEKNOLOGI PERTANIAN', 'TEKNOLOGI PERTANIAN', 'TEKNOLOGI PERTANIAN';
        	'program_studi' => 'BIOLOGI', 'AKUNTANSI', 'ILMU EKONOMI', 'MANAJEMEN', 'FARMASI', 'ILMU FILSAFAT', 'GEOGRAFI DAN ILMU LINGKUNGAN', 'KARTOGRAFI DAN PENGINDERAAN JAUH', 'PEMBANGUNAN WILAYAH', 'ILMU HUKUM', 'ANTROPOLOGI BUDAYA', 'ARKEOLOGI', 'BAHASA KOREA', 'ILMU SEJARAH', 'PARIWISATA', 'SASTRA ARAB', 'SASTRA INDONESIA', 'SASTRA INGGRIS', 'SASTRA JEPANG', 'SASTRA NUSANTARA', 'SASTRA PERANCIS', 'MANAJEMEN DAN KEBIJAKAN PUBLIK', 'ILMU HUBUNGAN INTERNASIONAL', 'ILMU KOMUNIKASI', 'ILMU PEMBANGUNAN SOSIAL DAN KESEJAHTERAAN', 'POLITIK DAN PEMERINTAHAN', 'SOSIOLOGI', 'GIZI KESEHATAN', 'ILMU KEPERAWATAN', 'PENDIDIKAN DOKTER', 'PENDIDIKAN DOKTER GIGI', 'ILMU KEPERAWATAN GIGI', 'KEDOKTERAN HEWAN', 'KEHUTANAN', 'ELEKTRONIKA DAN INSTRUMENTASI', 'FISIKA', 'GEOFISIKA', 'ILMU KOMPUTER', 'KIMIA', 'MATEMATIKA', 'STATISTIKA', 'AGRONOMI', 'BUDIDAYA PERIKANAN', 'ILMU HAMA & PENYAKIT TUMBUHAN', 'ILMU TANAH', 'MANAJ. SUMBER DAYA PERIKANAN', 'MIKROBIOLOGI PERTANIAN', 'PENYULUHAN & KOMUNIKASI PERTANIAN', 'SOS.EK. PERTANIAN (AGROBISNIS)', 'TEKNOLOGI HASIL PERIKANAN', 'ILMU DAN INDUSTRI PETERNAKAN', 'PSIKOLOGI', 'ARSITEKTUR', 'TEKNIK FISIKA', 'PERENCANAAN WILAYAH DAN KOTA', 'TEKNIK ELEKTRO', 'TEKNIK GEODESI', 'TEKNIK GEOLOGI', 'TEKNIK INDUSTRI', 'TEKNIK KIMIA', 'TEKNIK MESIN', 'TEKNIK NUKLIR', 'TEKNIK SIPIL', 'TEKNOLOGI INFORMASI', 'TEKNIK PERTANIAN', 'TEKNOLOGI INDUSTRI PERTANIAN', 'TEKNOLOGI PANGAN & HASIL PERTANIAN';
        ]);
    }
}
